Models:
  - User::User: -> Scaffolding
    - Username -> string
    - Password -> digest
    - admin -> boolean
    - has_one user_detail
    - has_many votes
    - User::UserDetail: -> Model
    - Name -> string
    - Gender -> string
    - Branch -> string 
    - Year -> int
    - Roll Number -> string
    - Course -> string
    - Section -> string
    - Email -> string
    - Avatar -> file
    - Residence? -> bool
    - Block -> string
    - Opt-in? -> bool
    - belongs_to user
    <%# Add more demographic parameters %>
  - Election::Candidate: -> Scaffolding
    - Affiliation -> string
    - belongs_to user
    - has_one candidate_detail
    - has_many elections, through nominations
  - Election::CandidateDetail: -> Model
    - CGPA -> decimal
    - Past Experiences -> string
    - Manifesto -> file
    - About Me -> text
    - belongs_to candidate
  - Election::Election: -> Scaffolding
    - Postion -> string
    - Deadline -> datetime
    - date_of_election -> datetime
    - session -> string 
    - has_many candidates, through nominations
    - belongs_to candidate, as winner
    - has_one vote_chain
  - Election::Nomination: -> Model
    - belongs_to candidate
    - belongs_to election
  - Election::VoteChain: -> Model
    - belongs_to election
    - vote_count -> text, serialized as array
    - has_many votes
  - Election::Vote: -> Model
    - prev_hash -> string
    - data -> int
    - hash -> text
    - belongs_to vote_chain
    - belongs_to user
    <%# Add more details relevant to block chain %>
  - Election::Event: -> Model
    - content -> text
